# -*- coding: utf-8 -*-
"""product_sesitment.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/gist/ANIKET-JAGTAP02/60e5c18f8b4d351338fcef5b9de076fd/product_sesitment.ipynb
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('ggplot')

import nltk
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('vader_lexicon')

# Read in data
df = pd.read_csv('/content/amazon.csv')
print(df.shape)
df = df.head(500)
print(df.shape)

df.head()

print(df.columns)

ax = df['score_average_rating'].value_counts().sort_index() \
    .plot(kind='bar',
          title='Count of Reviews by Stars',
          figsize=(10, 5))
ax.set_xlabel('Review Stars')
plt.show()

example = df['reviewText'][50]
print(example)

import nltk
nltk.download('punkt')

nltk.download('punkt_tab')

tokens = nltk.word_tokenize(example)
tokens[:10]

import nltk
nltk.download('averaged_perceptron_tagger')

nltk.download('averaged_perceptron_tagger_eng')

tagged = nltk.pos_tag(tokens)
tagged[:10]

import nltk

# Download everything required for NER (Named Entity Recognition)
nltk.download('maxent_ne_chunker')
nltk.download('words')
nltk.download('punkt')
nltk.download('averaged_perceptron_tagger')
nltk.download('maxent_ne_chunker_tab')  # for newer NLTK versions

entities = nltk.chunk.ne_chunk(tagged)
entities.pprint()

from nltk.sentiment import SentimentIntensityAnalyzer
from tqdm.notebook import tqdm

sia = SentimentIntensityAnalyzer()

sia.polarity_scores('I am so happy!')

sia.polarity_scores('This is the worst thing ever.')

sia.polarity_scores(example)

res = {}

for i, row in tqdm(df.iterrows(), total=len(df)):
    text = row['reviewText']           # correct column name
    myid = row['Unnamed: 0']           # unique identifier (or just use i)
    res[myid] = sia.polarity_scores(str(text))  # convert to string in case of NaN

vaders = pd.DataFrame(res).T
vaders = vaders.reset_index().rename(columns={'index': 'Unnamed: 0'})  # match your real key column

vaders = vaders.merge(df, on='Unnamed: 0', how='left')

# Now we have sentiment score and metadata
vaders.head()

ax = sns.barplot(data=vaders, x='score_average_rating', y='compound')
ax.set_title('Compund Score by Amazon Star Review')
plt.show()

fig, axs = plt.subplots(1, 3, figsize=(12, 3))

sns.barplot(data=vaders, x='overall', y='pos', ax=axs[0])
sns.barplot(data=vaders, x='overall', y='neu', ax=axs[1])
sns.barplot(data=vaders, x='overall', y='neg', ax=axs[2])

axs[0].set_title('Positive')
axs[1].set_title('Neutral')
axs[2].set_title('Negative')

for ax in axs:
    ax.set_xlabel('Amazon Star Rating')
    ax.set_ylabel('Average Sentiment Score')

plt.tight_layout()
plt.show()

from transformers import AutoTokenizer
from transformers import AutoModelForSequenceClassification
from scipy.special import softmax

MODEL = f"cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(MODEL)
model = AutoModelForSequenceClassification.from_pretrained(MODEL)

# VADER results on example
print(example)
sia.polarity_scores(example)

# Run for Roberta Model
encoded_text = tokenizer(example, return_tensors='pt')
output = model(**encoded_text)
scores = output[0][0].detach().numpy()
scores = softmax(scores)
scores_dict = {
    'roberta_neg' : scores[0],
    'roberta_neu' : scores[1],
    'roberta_pos' : scores[2]
}
print(scores_dict)

def polarity_scores_roberta(example):
    encoded_text = tokenizer(example, return_tensors='pt')
    output = model(**encoded_text)
    scores = output[0][0].detach().numpy()
    scores = softmax(scores)
    scores_dict = {
        'roberta_neg' : scores[0],
        'roberta_neu' : scores[1],
        'roberta_pos' : scores[2]
    }
    return scores_dict

res = {}

for i, row in tqdm(df.iterrows(), total=len(df)):
    try:
        text = str(row['reviewText'])           # ✅ your text column name
        myid = row['Unnamed: 0']                # ✅ your ID column (or use i)

        # VADER sentiment
        vader_result = sia.polarity_scores(text)
        vader_result_rename = {f"vader_{k}": v for k, v in vader_result.items()}

        # RoBERTa sentiment (assuming you've defined polarity_scores_roberta)
        roberta_result = polarity_scores_roberta(text)

        # Merge both model outputs
        both = {**vader_result_rename, **roberta_result}
        res[myid] = both

    except RuntimeError:
        print(f"Broke for id {myid}")
    except Exception as e:
        print(f"Error for id {myid}: {e}")

results_df = pd.DataFrame(res).T
results_df = results_df.reset_index().rename(columns={'index': 'Unnamed: 0'})  # match key column
results_df = results_df.merge(df, on='Unnamed: 0', how='left')

results_df.columns

sns.pairplot(data=results_df,
             vars=['vader_neg', 'vader_neu', 'vader_pos',
                  'roberta_neg', 'roberta_neu', 'roberta_pos'],
            hue='overall',
            palette='tab10')
plt.show()

results_df.query('overall == 1') \
    .sort_values('roberta_pos', ascending=False)['reviewText'].values[0]

results_df.query('overall == 1') \
    .sort_values('vader_pos', ascending=False)['reviewText'].values[0]

# nevative sentiment 5-Star view

results_df.query('overall == 5') \
    .sort_values('roberta_neg', ascending=False)['reviewText'].values[0]

results_df.query('overall == 5') \
    .sort_values('vader_neg', ascending=False)['reviewText'].values[0]

# netural sentiment 5-Star view

results_df.query('overall == 3') \
       .sort_values('vader_neu', ascending=False)['reviewText'].values[0]

results_df.query('overall == 3') \
        .sort_values('roberta_neu', ascending=False)['reviewText'].values[0]

from transformers import pipeline

sent_pipeline = pipeline("sentiment-analysis")

sent_pipeline('I love sentiment analysis!')

sent_pipeline('booo')

sent_pipeline('i  dont hate you')

sent_pipeline('The product meets expectations but doesn’t stand out')

sent_pipeline('It’s okay — not good, not bad')

sent_pipeline('It works, but file writes are a bit slower than expected on a USB3 reader')

result = sent_pipeline("Still don't feel it is very fast or is just my phone, I guess I will need to remove it and run some R/W tests. Still, it's ok.")
print(result)